### ISSUE TITLE
alfred 异常

### ISSUE THREAD

**Issue by Ran-Xing** [mofelee/alfred-quickref#1]
<img width="833" alt="image" src="https://user-images.githubusercontent.com/73819467/203014919-66a2af9e-0dc9-46a7-bdff-9fda685bf91a.png">

**Comment by mofelee** [comment]
![CleanShot 2022-11-21 at 18 51 46@2x](https://user-images.githubusercontent.com/5069410/203032387-d7e33d62-46fe-4bb5-aa1e-56b7f71dd24b.png)

可否提供下 log

**Comment by mofelee** [comment]
是否未更新到最新版本？

最新版本是0.4.2

我刚刚测试了一下，0.4.2是可以用的

**Comment by mofelee** [comment]
今天更新了一下数据的格式，如果使用 quickrefupdate 更新了数据会出现不可用的情况

https://github.com/jaywcjlove/reference/issues/105#issuecomment-1321499380

**Comment by Ran-Xing** [comment]
@mofelee 。。。叫我大哥，我教你啊

```bash
PATH=$PATH:$HOME/Library/pnpm/nodejs/16.16.0/bin/

if ! type node >/dev/null 2>&1; then
	osascript -e 'display alert "node 不存在！！" as critical'
fi

node ./index.js $1
```

**Comment by Ran-Xing** [comment]
学废了吗？

**Comment by Ran-Xing** [comment]
或者source ~/.zshrc

**Comment by mofelee** [comment]
需要安装 nodejs 才能正常运行代码
